// =============================================================================
// ZAMORIN CAFÉ ERP — RUNTIME SUPPORT MANIFEST GENERATOR
// Generates artifacts/runtime_support_manifest.json with Two-Dimensional Status
// =============================================================================

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = path.resolve(__dirname, '..');

const canonicalModules = [
  {
    id: "DASHBOARD_PRIMARY_MASTER",
    name: "Primary Master Command Centre Dashboard",
    family: "Dashboard",
    personas: ["MASTER"],
    route: "#dashboard",
    frontendFile: "frontend/src/js/pages/dashboardMaster.js",
    backendRoute: "backend/src/routes/dashboardRoutes.js",
    controller: "backend/src/controllers/dashboardController.js",
    exportSupport: "ZURF_PDF",
    uploadSupport: "NOT_APPLICABLE",
    receiptSupport: "NOT_APPLICABLE",
    documentType: "STATEMENT",
    testOwnership: "backend/test/dashboardCommandCentre.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "LOCAL_TEST_PASS",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  },
  {
    id: "DASHBOARD_OWNER",
    name: "Owner Portfolio Dashboard",
    family: "Dashboard",
    personas: ["OWNER"],
    route: "#dashboard",
    frontendFile: "frontend/src/js/pages/dashboardOwner.js",
    backendRoute: "backend/src/routes/dashboardRoutes.js",
    controller: "backend/src/controllers/dashboardController.js",
    exportSupport: "ZURF_PDF",
    uploadSupport: "NOT_APPLICABLE",
    receiptSupport: "NOT_APPLICABLE",
    documentType: "STATEMENT",
    testOwnership: "backend/test/ownerDashboardControl.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "LOCAL_TEST_PASS",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  },
  {
    id: "DASHBOARD_CAFE_OPS",
    name: "Cafe Operations Shift Dashboard",
    family: "Dashboard",
    personas: ["CAFE_ADMIN"],
    route: "#dashboard",
    frontendFile: "frontend/src/js/pages/dashboardAdmin.js",
    backendRoute: "backend/src/routes/dashboardRoutes.js",
    controller: "backend/src/controllers/dashboardController.js",
    exportSupport: "ZURF_PDF",
    uploadSupport: "NOT_APPLICABLE",
    receiptSupport: "NOT_APPLICABLE",
    documentType: "STATEMENT",
    testOwnership: "backend/test/cafeOperationsFoundation.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "LOCAL_TEST_PASS",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  },
  {
    id: "STAFF_HOME",
    name: "Staff / Employee Self-Service Home",
    family: "Staff Self-Service",
    personas: ["STAFF"],
    route: "#staff-home",
    frontendFile: "frontend/src/js/pages/staffHome.js",
    backendRoute: "backend/src/routes/employeeRoutes.js",
    controller: "backend/src/controllers/employeeController.js",
    exportSupport: "NOT_APPLICABLE",
    uploadSupport: "STAFF_DOCUMENTS",
    receiptSupport: "NOT_APPLICABLE",
    documentType: "NOT_APPLICABLE",
    testOwnership: "backend/test/employeeStaffDashboard.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "PRODUCTION_VALIDATION_PENDING",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  },
  {
    id: "POS_BILLING",
    name: "POS Billing, Till & Orders Terminal",
    family: "POS & Billing",
    personas: ["MASTER", "CAFE_ADMIN"],
    route: "#pos",
    frontendFile: "frontend/src/js/pages/posTill.js",
    backendRoute: "backend/src/routes/billRoutes.js",
    controller: "backend/src/controllers/billController.js",
    exportSupport: "THERMAL_RECEIPT_PDF",
    uploadSupport: "NOT_APPLICABLE",
    receiptSupport: "POS_CUSTOMER_RECEIPT",
    documentType: "RECEIPT",
    testOwnership: "backend/test/posBillingTerminal.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "LOCAL_TEST_PASS",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  },
  {
    id: "SALES_CASH_BOOK",
    name: "Sales & Cash Book Management",
    family: "Finance & Cash",
    personas: ["MASTER", "CAFE_ADMIN"],
    route: "#sales-cash",
    frontendFile: "frontend/src/js/pages/cashBook.js",
    backendRoute: "backend/src/routes/cashRoutes.js",
    controller: "backend/src/controllers/cashController.js",
    exportSupport: "CSV_XLSX_PDF",
    uploadSupport: "DENOMINATION_EVIDENCE",
    receiptSupport: "CASH_RECEIPT",
    documentType: "RECEIPT",
    testOwnership: "backend/test/businessModules.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "PRODUCTION_VALIDATION_PENDING",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  },
  {
    id: "ATTENDANCE_SHIFTS",
    name: "Attendance, Timeclock & Shifts",
    family: "Workforce Operations",
    personas: ["MASTER", "CAFE_ADMIN", "STAFF"],
    route: "#attendance",
    frontendFile: "frontend/src/js/modules/attendance/attendanceShifts.js",
    backendRoute: "backend/src/modules/attendance/attendanceRoutes.js",
    controller: "backend/src/modules/attendance/attendanceController.js",
    exportSupport: "CSV_XLSX",
    uploadSupport: "NOT_APPLICABLE",
    receiptSupport: "NOT_APPLICABLE",
    documentType: "STATEMENT",
    testOwnership: "backend/test/attendanceManagement.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "LOCAL_TEST_PASS",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  },
  {
    id: "INVENTORY_STOCK",
    name: "Inventory, Stock Register & FIFO Lots",
    family: "Inventory & Supply",
    personas: ["MASTER", "CAFE_ADMIN"],
    route: "#inventory",
    frontendFile: "frontend/src/js/pages/inventory.js",
    backendRoute: "backend/src/routes/inventoryRoutes.js",
    controller: "backend/src/controllers/inventoryController.js",
    exportSupport: "CSV_XLSX_PDF",
    uploadSupport: "BATCH_IMPORT_CSV",
    receiptSupport: "STOCK_TRANSFER_NOTE",
    documentType: "TRANSFER_NOTE",
    testOwnership: "backend/test/inventoryStockManagement.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "PRODUCTION_VALIDATION_PENDING",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  },
  {
    id: "PROCUREMENT_PURCHASING",
    name: "Procurement, Purchase Orders & 3-Way Match",
    family: "Procurement",
    personas: ["MASTER", "CAFE_ADMIN"],
    route: "#procurement",
    frontendFile: "frontend/src/js/pages/procurement.js",
    backendRoute: "backend/src/routes/procurementRoutes.js",
    controller: "backend/src/controllers/procurementController.js",
    exportSupport: "PURCHASE_ORDER_PDF",
    uploadSupport: "SUPPLIER_INVOICE_GRN",
    receiptSupport: "GOODS_RECEIPT_NOTE",
    documentType: "TRANSFER_NOTE",
    testOwnership: "backend/test/businessModules.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "PRODUCTION_VALIDATION_PENDING",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  },
  {
    id: "ASSET_MANAGEMENT",
    name: "Asset Register, Preventive Maintenance & PM 360",
    family: "Assets & Facilities",
    personas: ["MASTER", "CAFE_ADMIN"],
    route: "#assets",
    frontendFile: "frontend/src/js/pages/assets.js",
    backendRoute: "backend/src/routes/assetRoutes.js",
    controller: "backend/src/controllers/assetController.js",
    exportSupport: "ASSET_REGISTER_PDF",
    uploadSupport: "ASSET_MANUALS_INVOICES",
    receiptSupport: "MAINTENANCE_SERVICE_SLIP",
    documentType: "SERVICE_DOCUMENT",
    testOwnership: "backend/test/assetManagement.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "PRODUCTION_VALIDATION_PENDING",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  },
  {
    id: "QUALITY_FOOD_SAFETY",
    name: "Quality, Food Safety (FSMS), Cleaning & Checklists",
    family: "Quality & Compliance",
    personas: ["MASTER", "CAFE_ADMIN"],
    route: "#quality",
    frontendFile: "frontend/src/js/pages/quality.js",
    backendRoute: "backend/src/routes/qualityRoutes.js",
    controller: "backend/src/controllers/qualityController.js",
    exportSupport: "AUDIT_REPORT_PDF",
    uploadSupport: "INSPECTION_PHOTO_EVIDENCE",
    receiptSupport: "COMPLIANCE_CERTIFICATE",
    documentType: "CERTIFICATE",
    testOwnership: "backend/test/businessModules.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "PRODUCTION_VALIDATION_PENDING",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  },
  {
    id: "EMPLOYEES_HRIS",
    name: "Employee Directory & Workforce HRIS",
    family: "Human Resources",
    personas: ["MASTER", "OWNER"],
    route: "#employees",
    frontendFile: "frontend/src/js/pages/employees.js",
    backendRoute: "backend/src/routes/employeeRoutes.js",
    controller: "backend/src/controllers/employeeController.js",
    exportSupport: "EMPLOYEE_ROSTER_XLSX",
    uploadSupport: "KYC_EMPLOYMENT_DOCUMENTS",
    receiptSupport: "EMPLOYMENT_OFFER_LETTER",
    documentType: "LETTER",
    testOwnership: "backend/test/employeeWorkforceManagement.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "PRODUCTION_VALIDATION_PENDING",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  },
  {
    id: "PAYROLL_CONTROL",
    name: "Payroll Control, Statutory Rules & Payslips",
    family: "Human Resources",
    personas: ["MASTER", "OWNER"],
    route: "#payroll",
    frontendFile: "frontend/src/js/pages/payrollManagement.js",
    backendRoute: "backend/src/routes/payrollRoutes.js",
    controller: "backend/src/controllers/payrollController.js",
    exportSupport: "PAYSLIP_PDF_XLSX",
    uploadSupport: "BANK_DISBURSEMENT_REPORT",
    receiptSupport: "PAYSLIP_RECEIPT",
    documentType: "PAYSLIP",
    testOwnership: "backend/test/payrollMasterControl.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "PRODUCTION_VALIDATION_PENDING",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  },
  {
    id: "BILLS_INVOICES",
    name: "Owner Bills, Receipts & Invoice Attachment Viewer",
    family: "Finance & Accounts",
    personas: ["MASTER", "OWNER"],
    route: "#bills",
    frontendFile: "frontend/src/js/pages/ownerBills.js",
    backendRoute: "backend/src/routes/billRoutes.js",
    controller: "backend/src/controllers/billController.js",
    exportSupport: "BILLS_LEDGER_PDF",
    uploadSupport: "BILL_RECEIPT_ATTACHMENTS",
    receiptSupport: "VENDOR_BILL_RECEIPT",
    documentType: "RECEIPT",
    testOwnership: "backend/test/ownerSalesBills.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "PRODUCTION_VALIDATION_PENDING",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  },
  {
    id: "EXPENSES_VOUCHERS",
    name: "Expense Vouchers, Approvals & Petty Cash",
    family: "Finance & Accounts",
    personas: ["MASTER", "CAFE_ADMIN"],
    route: "#expenses",
    frontendFile: "frontend/src/js/pages/expenses.js",
    backendRoute: "backend/src/routes/expenseRoutes.js",
    controller: "backend/src/controllers/expenseController.js",
    exportSupport: "EXPENSE_STATEMENT_PDF",
    uploadSupport: "EXPENSE_RECEIPT_PHOTO",
    receiptSupport: "PETTY_CASH_VOUCHER",
    documentType: "VOUCHER",
    testOwnership: "backend/test/expenseManagement.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "PRODUCTION_VALIDATION_PENDING",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  },
  {
    id: "FINANCE_GENERAL_LEDGER",
    name: "Finance Hub, General Ledger, Journals & AP/AR",
    family: "Finance & Accounts",
    personas: ["MASTER", "OWNER"],
    route: "#finance",
    frontendFile: "frontend/src/js/pages/financeAccounts.js",
    backendRoute: "backend/src/routes/financeRoutes.js",
    controller: "backend/src/controllers/financeController.js",
    exportSupport: "FINANCIAL_STATEMENTS_PDF_XLSX",
    uploadSupport: "BANK_STATEMENT_IMPORT",
    receiptSupport: "JOURNAL_POSTING_VOUCHER",
    documentType: "VOUCHER",
    testOwnership: "backend/test/financeAccounting.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "PRODUCTION_VALIDATION_PENDING",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  },
  {
    id: "PERSONAL_LEDGER",
    name: "Primary Master Personal Ledger & Owner Settlements",
    family: "Finance & Treasury",
    personas: ["MASTER", "OWNER"],
    route: "#ledger",
    frontendFile: "frontend/src/js/pages/personalLedger.js",
    backendRoute: "backend/src/routes/personalLedgerRoutes.js",
    controller: "backend/src/controllers/personalLedgerController.js",
    exportSupport: "LEDGER_STATEMENT_PDF",
    uploadSupport: "SETTLEMENT_CONFIRMATION_PROOF",
    receiptSupport: "SETTLEMENT_ACKNOWLEDGEMENT",
    documentType: "ACKNOWLEDGEMENT",
    testOwnership: "backend/test/personalLedgerMasterControl.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "PRODUCTION_VALIDATION_PENDING",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  },
  {
    id: "PASSBOOK_TREASURY",
    name: "Passbook & Multi-Account Treasury Vault",
    family: "Finance & Treasury",
    personas: ["MASTER", "OWNER"],
    route: "#passbook",
    frontendFile: "frontend/src/js/pages/passbook.js",
    backendRoute: "backend/src/routes/passbookRoutes.js",
    controller: "backend/src/controllers/passbookController.js",
    exportSupport: "PASSBOOK_STATEMENT_PDF_XLSX_CSV",
    uploadSupport: "BANK_STATEMENT_CSV",
    receiptSupport: "TREASURY_TRANSFER_RECEIPT",
    documentType: "ACKNOWLEDGEMENT",
    testOwnership: "backend/test/passbookTreasury.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "PRODUCTION_VALIDATION_PENDING",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  },
  {
    id: "CUSTOMERS_LOYALTY",
    name: "Customer Directory, 360 & Loyalty Points Ledger",
    family: "Commercial & CRM",
    personas: ["MASTER", "CAFE_ADMIN"],
    route: "#customers",
    frontendFile: "frontend/src/js/pages/customers.js",
    backendRoute: "backend/src/routes/customerRoutes.js",
    controller: "backend/src/controllers/customerController.js",
    exportSupport: "CUSTOMER_LEDGER_CSV",
    uploadSupport: "CUSTOMER_IMPORT_CSV",
    receiptSupport: "LOYALTY_REDEMPTION_SLIP",
    documentType: "VOUCHER",
    testOwnership: "backend/test/customerLoyaltyManagement.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "PRODUCTION_VALIDATION_PENDING",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  },
  {
    id: "MENU_MANAGEMENT",
    name: "Global Menu Master, BOM Recipes & Pricing",
    family: "Commercial & Menu",
    personas: ["MASTER"],
    route: "#menu",
    frontendFile: "frontend/src/js/pages/menuManagement.js",
    backendRoute: "backend/src/routes/menuRoutes.js",
    controller: "backend/src/controllers/menuController.js",
    exportSupport: "MENU_CATALOGUE_PDF",
    uploadSupport: "ITEM_IMAGE_ASSETS",
    receiptSupport: "NOT_APPLICABLE",
    documentType: "STATEMENT",
    testOwnership: "backend/test/menuRecipeManagement.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "PRODUCTION_VALIDATION_PENDING",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  },
  {
    id: "VENDORS_SUPPLIERS",
    name: "Supplier Directory, Onboarding & Bank Maker-Checker",
    family: "Commercial & Vendors",
    personas: ["MASTER"],
    route: "#vendors",
    frontendFile: "frontend/src/js/pages/vendors.js",
    backendRoute: "backend/src/routes/vendorRoutes.js",
    controller: "backend/src/controllers/vendorController.js",
    exportSupport: "VENDOR_LIST_XLSX",
    uploadSupport: "VENDOR_GSTIN_BANK_PROOFS",
    receiptSupport: "VENDOR_ONBOARDING_LETTER",
    documentType: "LETTER",
    testOwnership: "backend/test/businessModules.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "PRODUCTION_VALIDATION_PENDING",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  },
  {
    id: "REVENUE_SHARE",
    name: "Revenue Share & Leased Outlet Agreements",
    family: "Commercial & Contracts",
    personas: ["MASTER", "OWNER"],
    route: "#revenue-share",
    frontendFile: "frontend/src/js/pages/revenueShare.js",
    backendRoute: "backend/src/routes/revenueShareRoutes.js",
    controller: "backend/src/controllers/revenueShareController.js",
    exportSupport: "SETTLEMENT_REPORT_PDF",
    uploadSupport: "AGREEMENT_CONTRACT_PDF",
    receiptSupport: "REVENUE_SHARE_SETTLEMENT_INVOICE",
    documentType: "STATEMENT",
    testOwnership: "backend/test/businessModules.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "BLOCKED_BUSINESS_DECISION (ACT-017 & ACT-018)",
    productionStatus: "PRODUCTION_VALIDATION_PENDING",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  },
  {
    id: "TASKS_APPROVALS",
    name: "Operational Tasks, Approvals & Oversight Queue",
    family: "Operations & Governance",
    personas: ["MASTER", "OWNER", "CAFE_ADMIN"],
    route: "#tasks",
    frontendFile: "frontend/src/js/pages/tasksApprovals.js",
    backendRoute: "backend/src/routes/taskRoutes.js",
    controller: "backend/src/controllers/taskController.js",
    exportSupport: "TASK_SUMMARY_PDF",
    uploadSupport: "TASK_COMPLETION_EVIDENCE",
    receiptSupport: "NOT_APPLICABLE",
    documentType: "STATEMENT",
    testOwnership: "backend/test/businessModules.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "PRODUCTION_VALIDATION_PENDING",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  },
  {
    id: "REPORTS_ANALYTICS",
    name: "Reports & Analytics Control Centre / ZURF Export",
    family: "Insights & Analytics",
    personas: ["MASTER", "OWNER", "CAFE_ADMIN"],
    route: "#reports",
    frontendFile: "frontend/src/js/pages/reportsAnalytics.js",
    backendRoute: "backend/src/routes/reportRoutes.js",
    controller: "backend/src/controllers/reportController.js",
    exportSupport: "ZURF_FULL_SUITE_PDF_XLSX_CSV",
    uploadSupport: "NOT_APPLICABLE",
    receiptSupport: "NOT_APPLICABLE",
    documentType: "STATEMENT",
    testOwnership: "backend/test/ownerReportsAnalyticsParity.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "PRODUCTION_VALIDATION_PENDING",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  },
  {
    id: "SYSTEM_ADMINISTRATION",
    name: "System Administration, Roles, Users & Cafe Setup",
    family: "Administration",
    personas: ["MASTER"],
    route: "#admin",
    frontendFile: "frontend/src/js/pages/administration.js",
    backendRoute: "backend/src/routes/adminRoutes.js",
    controller: "backend/src/controllers/adminGovernanceController.js",
    exportSupport: "SYSTEM_AUDIT_LOG_CSV",
    uploadSupport: "NOT_APPLICABLE",
    receiptSupport: "NOT_APPLICABLE",
    documentType: "STATEMENT",
    testOwnership: "backend/test/adminGovernance.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "LOCAL_TEST_PASS",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  },
  {
    id: "CAFE_OPS_DEVICES",
    name: "Cafe Operations Device Trust & Session Management",
    family: "System & Devices",
    personas: ["MASTER", "CAFE_ADMIN"],
    route: "#cafe-ops-devices",
    frontendFile: "frontend/src/js/pages/cafeOperationsDevices.js",
    backendRoute: "backend/src/routes/deviceRoutes.js",
    controller: "backend/src/controllers/deviceController.js",
    exportSupport: "DEVICE_SECURITY_AUDIT_PDF",
    uploadSupport: "NOT_APPLICABLE",
    receiptSupport: "NOT_APPLICABLE",
    documentType: "STATEMENT",
    testOwnership: "backend/test/deviceBoundAttendanceFinal.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "LOCAL_TEST_PASS",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  },
  {
    id: "SETTINGS_PREFERENCES",
    name: "Universal User Settings, Account & Preferences",
    family: "System & Profile",
    personas: ["MASTER", "OWNER", "CAFE_ADMIN", "STAFF"],
    route: "#settings",
    frontendFile: "frontend/src/js/pages/settingsShared.js",
    backendRoute: "backend/src/routes/settingsRoutes.js",
    controller: "backend/src/controllers/settingsController.js",
    exportSupport: "GDPR_DATA_EXPORT_JSON",
    uploadSupport: "AVATAR_IMAGE",
    receiptSupport: "NOT_APPLICABLE",
    documentType: "STATEMENT",
    testOwnership: "backend/test/employeeProfileApi.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "PRODUCTION_VALIDATION_PENDING",
    userReviewStatus: "USER_REVIEW_PENDING",
    retiredStatus: "ACTIVE"
  },
  {
    id: "TRASH_DATA_RECOVERY",
    name: "Trash Bin & Governed 30-Day Soft-Delete Retention",
    family: "System & Recovery",
    personas: ["MASTER"],
    route: "#trash",
    frontendFile: "frontend/src/js/pages/trashBin.js",
    backendRoute: "backend/src/routes/trashRoutes.js",
    controller: "backend/src/controllers/trashController.js",
    exportSupport: "PURGE_LOG_CSV",
    uploadSupport: "NOT_APPLICABLE",
    receiptSupport: "NOT_APPLICABLE",
    documentType: "STATEMENT",
    testOwnership: "backend/test/businessModules.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "LOCAL_TEST_PASS",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  },
  {
    id: "ANNOUNCEMENTS_NOTIFICATIONS",
    name: "Corporate Announcements & Communications",
    family: "System & Communications",
    personas: ["MASTER", "OWNER", "CAFE_ADMIN", "STAFF"],
    route: "#announcements",
    frontendFile: "frontend/src/js/pages/announcements.js",
    backendRoute: "backend/src/routes/notificationRoutes.js",
    controller: "backend/src/controllers/notificationController.js",
    exportSupport: "NOT_APPLICABLE",
    uploadSupport: "ANNOUNCEMENT_ATTACHMENT",
    receiptSupport: "NOT_APPLICABLE",
    documentType: "STATEMENT",
    testOwnership: "backend/test/businessModules.test.js",
    supportStatus: "COMPLETE",
    businessStatus: "READY",
    productionStatus: "PRODUCTION_VALIDATION_PENDING",
    userReviewStatus: "APPROVED",
    retiredStatus: "ACTIVE"
  }
];

const manifest = {
  timestamp: new Date().toISOString(),
  totalModules: canonicalModules.length,
  supportCompleteCount: canonicalModules.filter(m => m.supportStatus.startsWith("COMPLETE")).length,
  businessBlockedCount: canonicalModules.filter(m => m.businessStatus.startsWith("BLOCKED")).length,
  userReviewPendingCount: canonicalModules.filter(m => m.userReviewStatus.startsWith("USER_REVIEW_PENDING")).length,
  productionPendingCount: canonicalModules.filter(m => m.productionStatus.includes("PENDING")).length,
  modules: canonicalModules
};

const targetPath = path.join(ROOT_DIR, 'artifacts/runtime_support_manifest.json');
fs.writeFileSync(targetPath, JSON.stringify(manifest, null, 2), 'utf8');
console.log(`✔ Generated ${targetPath} with ${canonicalModules.length} modules.`);
