'use strict';

const DEVICE_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  REVOKED: 'REVOKED',
  LOST: 'LOST',
  RETIRED: 'RETIRED',
  REPLACED: 'REPLACED',
});

const SESSION_TYPE = Object.freeze({
  OPERATOR_PIN: 'OPERATOR_PIN',
  MASTER_ACCOUNT: 'MASTER_ACCOUNT',
});

// This module only ever runs one workspace. The field still exists
// explicitly on the session record (rather than being implied) because the
// Master spec is emphatic that workspace and role are separate concepts and
// audit records must show both — see ARCHITECTURE_DECISIONS.md section 2.
const WORKSPACE_MODE = Object.freeze({
  CAFE_OPERATIONS: 'CAFE_OPERATIONS',
});

const ACTOR_ROLE = Object.freeze({
  CAFE_ADMIN: 'CAFE_ADMIN',
  MASTER_PRIMARY: 'MASTER_PRIMARY',
});

const AUTH_METHOD = Object.freeze({
  OPERATOR_PIN: 'OPERATOR_PIN',
  MASTER_PASSWORD: 'MASTER_PASSWORD',
  MASTER_PASSWORD_MFA: 'MASTER_PASSWORD_MFA',
  MASTER_PASSKEY: 'MASTER_PASSKEY',
});

const AUTH_STRENGTH = Object.freeze({
  STANDARD: 'STANDARD', // operator PIN
  STRONG: 'STRONG',     // master password(+MFA)/passkey
});

const OPERATOR_ACCESS_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  REVOKED: 'REVOKED',
});

const SESSION_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  LOCKED: 'LOCKED',
  ENDED: 'ENDED',
});

// Union of both specs' end-reason vocabularies (login spec Section 75,
// master spec Section 135) — reconciled into one enum since both session
// types share one lifecycle table.
const SESSION_END_REASON = Object.freeze({
  MANUAL_END: 'MANUAL_END',
  SWITCH_OPERATOR: 'SWITCH_OPERATOR',
  INACTIVITY_EXPIRY: 'INACTIVITY_EXPIRY',
  OVERALL_EXPIRY: 'OVERALL_EXPIRY',
  ABNORMAL_TERMINATION: 'ABNORMAL_TERMINATION',
  ACCESS_REVOKED: 'ACCESS_REVOKED',       // Operator Access grant revoked
  ROLE_REVOKED: 'ROLE_REVOKED',           // Master authority revoked
  EMPLOYEE_DEACTIVATED: 'EMPLOYEE_DEACTIVATED',
  CAFE_ASSIGNMENT_REMOVED: 'CAFE_ASSIGNMENT_REMOVED',
  TEMP_ACCESS_EXPIRED: 'TEMP_ACCESS_EXPIRED',
  DEVICE_REVOKED: 'DEVICE_REVOKED',
  DEVICE_LOST: 'DEVICE_LOST',
  DEVICE_RETIRED: 'DEVICE_RETIRED',
  DEVICE_REPLACED: 'DEVICE_REPLACED',
  DEVICE_REASSIGNED: 'DEVICE_REASSIGNED', // device's cafe changed mid-session
  REMOTE_REVOKED: 'REMOTE_REVOKED',       // governance ended it remotely
  SECURITY_EVENT: 'SECURITY_EVENT',
});

// Internal-only reason codes. These NEVER reach the client response body —
// the client only ever sees the generic "Unable to Sign In" family of
// messages (login spec Section 49 / master spec Section 35). They exist so
// audit logs and support-reference lookups can distinguish what actually
// happened.
const DENIAL_REASON = Object.freeze({
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  DEVICE_NOT_ACTIVE: 'DEVICE_NOT_ACTIVE',
  INVALID_PIN: 'INVALID_PIN',
  EMPLOYEE_INACTIVE: 'EMPLOYEE_INACTIVE',
  CAFE_MISMATCH: 'CAFE_MISMATCH',
  ACCESS_MISSING: 'ACCESS_MISSING',
  ACCESS_EXPIRED: 'ACCESS_EXPIRED',
  ACCESS_REVOKED: 'ACCESS_REVOKED',
  MASTER_AUTH_FAILED: 'MASTER_AUTH_FAILED',
  MASTER_INACTIVE: 'MASTER_INACTIVE',
  ORG_MISMATCH: 'ORG_MISMATCH',
  SECURITY_BLOCKED: 'SECURITY_BLOCKED',
});

const SECURITY_EVENT_TYPE = Object.freeze({
  DEVICE_ENROLLED: 'DEVICE_ENROLLED',
  DEVICE_ENROLLMENT_FAILED: 'DEVICE_ENROLLMENT_FAILED',
  DEVICE_REASSIGNED_EVENT: 'DEVICE_REASSIGNED_EVENT',
  OPERATOR_SIGNIN_SUCCESS: 'OPERATOR_SIGNIN_SUCCESS',
  OPERATOR_SIGNIN_FAILED: 'OPERATOR_SIGNIN_FAILED',
  MASTER_SIGNIN_SUCCESS: 'MASTER_SIGNIN_SUCCESS',
  MASTER_SIGNIN_FAILED: 'MASTER_SIGNIN_FAILED',
  SIGNIN_THROTTLED: 'SIGNIN_THROTTLED',
  SESSION_LOCKED: 'SESSION_LOCKED',
  SESSION_UNLOCKED: 'SESSION_UNLOCKED',
  SESSION_REAUTH_FAILED: 'SESSION_REAUTH_FAILED',
  STEP_UP_CONFIRMED: 'STEP_UP_CONFIRMED',
  STEP_UP_FAILED: 'STEP_UP_FAILED',
  SESSION_SWITCHED: 'SESSION_SWITCHED',
  SESSION_ENDED: 'SESSION_ENDED',
  SESSION_EXPIRED_EVENT: 'SESSION_EXPIRED_EVENT',
  SESSION_ENDED_REMOTELY: 'SESSION_ENDED_REMOTELY',
  CAFE_MISMATCH_ATTEMPT: 'CAFE_MISMATCH_ATTEMPT',
  DEVICE_LIFECYCLE_EVENT: 'DEVICE_LIFECYCLE_EVENT',
  STALE_SESSION_RECOVERED: 'STALE_SESSION_RECOVERED',
  STALE_SESSION_TERMINATED: 'STALE_SESSION_TERMINATED',
  CONCURRENT_SESSION_DETECTED: 'CONCURRENT_SESSION_DETECTED',
  SUPPORT_REFERENCE_ISSUED: 'SUPPORT_REFERENCE_ISSUED',
});

module.exports = {
  DEVICE_STATUS, SESSION_TYPE, WORKSPACE_MODE, ACTOR_ROLE, AUTH_METHOD, AUTH_STRENGTH,
  OPERATOR_ACCESS_STATUS, SESSION_STATUS, SESSION_END_REASON, DENIAL_REASON, SECURITY_EVENT_TYPE,
};
